"""Updated models with new structure

Revision ID: 76cccd3b7c43
Revises: cb172dd9c5d7
Create Date: 2025-01-29 14:37:47.062700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76cccd3b7c43'
down_revision = 'cb172dd9c5d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_brands',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'brand_id')
    )
    op.drop_table('stores')
    op.drop_table('usages')
    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=False))
        batch_op.alter_column('expiry_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.drop_constraint('fk_coupons_store_id_stores', type_='foreignkey')
        batch_op.create_foreign_key(None, 'brands', ['brand_id'], ['id'])
        batch_op.drop_column('created_at')
        batch_op.drop_column('store_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))

    with op.batch_alter_table('coupons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_coupons_store_id_stores', 'stores', ['store_id'], ['id'])
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.drop_column('brand_id')

    op.create_table('usages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('coupon_id', sa.INTEGER(), nullable=False),
    sa.Column('store_id', sa.INTEGER(), nullable=False),
    sa.Column('used_at', sa.DATETIME(), nullable=True),
    sa.Column('amount_saved', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], name='fk_usages_coupon_id_coupons'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name='fk_usages_store_id_stores'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_usages_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stores',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_brands')
    op.drop_table('brands')
    # ### end Alembic commands ###
